// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-o7GE3GXOeGaDm7VoO8zHg1kPZ8eKhE',
    appId: '1:197971182074:web:e449ef551b34a7ce532443',
    messagingSenderId: '197971182074',
    projectId: 'budgetbox-79af2',
    authDomain: 'budgetbox-79af2.firebaseapp.com',
    storageBucket: 'budgetbox-79af2.firebasestorage.app',
    measurementId: 'G-E4V0NNLP80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOgkRvTAdXdnOGWl5PezoDlbJPMyyAlBg',
    appId: '1:197971182074:android:afc69f070dd554ba532443',
    messagingSenderId: '197971182074',
    projectId: 'budgetbox-79af2',
    storageBucket: 'budgetbox-79af2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMigMcID0MdgNsbg4Us__ak0AGrd-JuE',
    appId: '1:197971182074:ios:0e4c822046336e8c532443',
    messagingSenderId: '197971182074',
    projectId: 'budgetbox-79af2',
    storageBucket: 'budgetbox-79af2.firebasestorage.app',
    iosBundleId: 'com.example.budgetbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaMigMcID0MdgNsbg4Us__ak0AGrd-JuE',
    appId: '1:197971182074:ios:0e4c822046336e8c532443',
    messagingSenderId: '197971182074',
    projectId: 'budgetbox-79af2',
    storageBucket: 'budgetbox-79af2.firebasestorage.app',
    iosBundleId: 'com.example.budgetbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW-o7GE3GXOeGaDm7VoO8zHg1kPZ8eKhE',
    appId: '1:197971182074:web:8eb1783894d8c570532443',
    messagingSenderId: '197971182074',
    projectId: 'budgetbox-79af2',
    authDomain: 'budgetbox-79af2.firebaseapp.com',
    storageBucket: 'budgetbox-79af2.firebasestorage.app',
    measurementId: 'G-TDFY146Y6P',
  );
}
